### ISSUE TITLE
TypeError: Not a buffer

### ISSUE THREAD

**Issue by tuoxie007** [qiniu/nodejs-sdk#134]
TypeError: Not a buffer
  at TypeError (native)
  at new Hmac (crypto.js:136:16)
  at Object.Hmac (crypto.js:134:12)
  at Object.exports.hmacSha1 (/home/node/api/source/node_modules/qiniu/qiniu/util.js:25:21)
  at PutPolicy.token (/home/node/api/source/node_modules/qiniu/qiniu/rs.js:158:22)
...

在阿里云上有问题(node版本0.12.2)，在我mac的开发机(node版本0.12.0)上没问题，代码完全一致

**Comment by tuoxie007** [comment]
是配置的问题

**Comment by linesh-simplicity** [comment]
Hi @tuoxie007 ，我现在也遇到同样的问题，不知道你还记得解决方案是什么嘛？请教一下呢。

以下是我用的版本和配置，如果需要更多的信息请让我知道。

```package.json
{
    "dependencies": {
         "qiniu": "^6.1.11"
    }
}
```
```
node -v
v6.1.0
```

**Comment by zhoushuren** [comment]
我也遇到这同样的问题，Node版本v6.9.1，求解答。

**Comment by linesh-simplicity** [comment]
我忘记了当初是如何解决的，不过最后写出来的七牛脚本和配置在这里，如果有用你可以参考一下哈。

https://github.com/linesh-simplicity/translation-spring-mvc-4-documentation/blob/master/build/utils/qiniu.js
