### ISSUE TITLE
间歇性上次失败, 报错: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by yinxin630** [qiniu/nodejs-sdk#210]
有时候会出现上次失败的情况, 报错信息为: 

```
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^
Error: getaddrinfo ENOTFOUND upload-z1.qiniu.com upload-z1.qiniu.com:80
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
```

环境为 node@6.9.4, qiniu@6.1.13

**Comment by KevinOfNeu** [comment]
+ 1

**Comment by jemygraw** [comment]
dns解析问题

**Comment by Joeycz** [comment]
这个问题后来怎么解决的啊？

**Comment by jemygraw** [comment]
dns解析的问题，一般得查查网络配置了，语言层面比较无辜

**Comment by edwardfhsiao** [comment]
换了dns也没用，不知道如何解决

**Comment by tradzero** [comment]
@jemygraw DNS问题的话 我直接hosts写死对应地址 一样报错
