### ISSUE TITLE
上传文件的时候报411错误

### ISSUE THREAD

**Issue by Andyliwr** [qiniu/nodejs-sdk#213]
```
{ code: 411,
  error: 
   SyntaxError: Unexpected token < in JSON at position 0
       at Object.parse (native)
       at IncomingMessage.<anonymous> (C:\Users\Andyliwr\Documents\graduationDesign\reptile\node_modules\.0.5.1@urllib\lib\urllib.js:292:25)
       at emitNone (events.js:91:20)
       at IncomingMessage.emit (events.js:185:7)
       at endReadableNT (_stream_readable.js:926:12)
       at _combinedTickCallback (internal/process/next_tick.js:74:11)
       at process._tickCallback (internal/process/next_tick.js:98:9) }

Process finished with exit code 0
```

打断点发现，返回的数据是一个错误的HTML文档：
```
ERROR
The requested URL could not be retrieved
While trying to process the request:

              POST / HTTP/1.1
Content-Type: multipart/form-data; boundary=--------------------------020538678673918244844991
User-Agent: QiniuNodejs/6.1.13 (Windows_NT; win32; x64; )
Accept: application/json
Host: upload-z2.qiniu.com
Connection: keep-alive
Transfer-Encoding: chunked

            
The following error was encountered:

Invalid Request

Some aspect of the HTTP Request is invalid. Possible problems:

Missing or unknown request method
Missing URL
Missing HTTP Identifier (HTTP/1.0)
Request is too large
Content-Length missing for POST or PUT requests
Illegal character in hostname; underscores are not allowed
```
求告诉这个是怎么回事?

**Comment by Andyliwr** [comment]
找到原因了，根据官方给的nodejs的demo运行不一定会成功，少了一些设置的步骤：
```
qiniu.conf.SCHEME = 'https';
qiniu.conf.UP_HTTPS_HOST = 'https://up-z2.qbox.me';
````
加上这个就好了，每个区域都有自己的UP_HTTPS_HOST ，参照下面：
存储区域对应 HTTPS 地址，参考[官方文档](https://support.qiniu.com/hc/kb/article/210702)

| 存储区域 | 区域代码 | HTTPS 地址               |
| ---- | ---- | ---------------------- |
| 华东   | ECN  | https://up.qbox.me     |
| 华北   | NCN  | https://up-z1.qbox.me  |
| 华南   | SCN  | https://up-z2.qbox.me  |
| 北美   | NA   | https://up-na0.qbox.me |

**Comment by Azard** [comment]
我也同样的错误

**Comment by jemygraw** [comment]
后续不需要在手动设置up hosts，参考：https://github.com/qiniu/nodejs-sdk/blob/master/examples/
