### ISSUE TITLE
无法通过new Mac设置 accessKey 和 secretKey

### ISSUE THREAD

**Issue by jakechan2012** [qiniu/nodejs-sdk#263]
sdk版本 `7.0.8`
根据[官方文档](https://developer.qiniu.com/kodo/sdk/1289/nodejs#5)，是通过以下方式来设置 accessKey 和 secretKey
```
var accessKey = 'your access key';
var secretKey = 'your secret key';
var mac = new qiniu.auth.digest.Mac(accessKey, secretKey);
```
但是会得到以下`token`
```
<PLEASE APPLY YOUR ACCESS KEY>:vZFWIoYmT1R7kdOm_omQAdOK74k=:eyJzY29wZSI6Im5ibGl0eSIsImRlYWRsaW5lIjoxNTA1MDQwNTgyfQ==
```
和错误提示
```
Error: 612
{"error":"app/accesskey is not found"}
    at /Users/jake/Projects/Personal/jake.nblity/node_modules/qiniu/qiniu/zone.js:66:17
    at done (/Users/jake/Projects/Personal/jake.nblity/node_modules/urllib/lib/urllib.js:444:5)
    at /Users/jake/Projects/Personal/jake.nblity/node_modules/urllib/lib/urllib.js:693:9
    at decodeContent (/Users/jake/Projects/Personal/jake.nblity/node_modules/urllib/lib/urllib.js:517:14)
    at IncomingMessage.<anonymous> (/Users/jake/Projects/Personal/jake.nblity/node_modules/urllib/lib/urllib.js:658:7)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**通过v6的设置方式就可以解决**
```
qiniu.conf.ACCESS_KEY = qiniuKey.accessKey;
qiniu.conf.SECRET_KEY = qiniuKey.secretKey;
let mac = qiniu.auth.digest.Mac();
```

以上是否属于BUG？

**Comment by jemygraw** [comment]
目前测试没有BUG，请确认你这种写法中，ak，sk都填对了。
```
var accessKey = 'your access key';
var secretKey = 'your secret key';
var mac = new qiniu.auth.digest.Mac(accessKey, secretKey);
```

**Comment by jakechan2012** [comment]
@jemygraw 刚刚重新测试了以下，可以构造函数传参，并且在一个新的目录以及虚拟机中测试，确实通过了。 可能开始我的代码存在一些问题。
给您带来麻烦了。
