### ISSUE TITLE
调用bucketManager.listPrefix 直接报错

### ISSUE THREAD

**Issue by roy201603** [qiniu/nodejs-sdk#283]
用了配置好秘钥和bucket后，调用example/rs_list_prefix.js 下面的例子直接报错，只要用到资源管理这个类BucketManager都会报错 ，这个是什么问题呢

`{ JSONResponseFormatError: Unexpected token < in JSON at position 0 (data json format: "Moved"), POST http://rsf.qiniu.com/list?bucket=qianyi&prefix=&limit=10&marker=&delimiter= 302 (connected: true, keepalive socket: false)
headers: {"location":"http://172.16.40.253:80/disable/disable.htm?url_type=%E8%AE%BF%E9%97%AE%E7%BD%91%E7%AB%99/%49%54%E8%A1%8C%E4%B8%9A&plc_name=%E7%A6%81%E6%AD%A2%E9%83%A8%E5%88%86%E4%B8%8A%E7%BD%91","content-type":"text/html;","content-length":"14"}
    at JSON.parse (<anonymous>)
    at parseJSON (/Users/wing/bw-source/static/node_modules/urllib/lib/urllib.js:894:24)
    at /Users/wing/bw-source/static/node_modules/urllib/lib/urllib.js:677:23
    at decodeContent (/Users/wing/bw-source/static/node_modules/urllib/lib/urllib.js:517:14)
    at IncomingMessage.<anonymous> (/Users/wing/bw-source/static/node_modules/urllib/lib/urllib.js:658:7)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'JSONResponseFormatError',
  data: 'Moved',
  path: '/list?bucket=qianyi&prefix=&limit=10&marker=&delimiter=',
  status: 302,
  headers: 
   { location: 'http://172.16.40.253:80/disable/disable.htm?url_type=%E8%AE%BF%E9%97%AE%E7%BD%91%E7%AB%99/%49%54%E8%A1%8C%E4%B8%9A&plc_name=%E7%A6%81%E6%AD%A2%E9%83%A8%E5%88%86%E4%B8%8A%E7%BD%91',
     'content-type': 'text/html;',
     'content-length': '14' },
  res: 
   { status: 302,
     statusCode: 302,
     headers: 
      { location: 'http://172.16.40.253:80/disable/disable.htm?url_type=%E8%AE%BF%E9%97%AE%E7%BD%91%E7%AB%99/%49%54%E8%A1%8C%E4%B8%9A&plc_name=%E7%A6%81%E6%AD%A2%E9%83%A8%E5%88%86%E4%B8%8A%E7%BD%91',
        'content-type': 'text/html;',
        'content-length': '14' },
     size: 14,
     aborted: false,
     rt: 70,
     keepAliveSocket: false,
     data: 'Moved',
     requestUrls: [ 'http://rsf.qiniu.com/list?bucket=qianyi&prefix=&limit=10&marker=&delimiter=' ],
     timing: null,
     remoteAddress: '23.236.118.210',
     remotePort: 80 } }
/Users/wing/bw-source/static/node_modules/qiniu/examples/rs_list_prefix.js:25
    throw err;
    ^

JSONResponseFormatError: Unexpected token < in JSON at position 0 (data json format: "Moved"), POST http://rsf.qiniu.com/list?bucket=qianyi&prefix=&limit=10&marker=&delimiter= 302 (connected: true, keepalive socket: false)
headers: {"location":"http://172.16.40.253:80/disable/disable.htm?url_type=%E8%AE%BF%E9%97%AE%E7%BD%91%E7%AB%99/%49%54%E8%A1%8C%E4%B8%9A&plc_name=%E7%A6%81%E6%AD%A2%E9%83%A8%E5%88%86%E4%B8%8A%E7%BD%91","content-type":"text/html;","content-length":"14"}
    at JSON.parse (<anonymous>)
    at parseJSON (/Users/wing/bw-source/static/node_modules/urllib/lib/urllib.js:894:24)
    at /Users/wing/bw-source/static/node_modules/urllib/lib/urllib.js:677:23
    at decodeContent (/Users/wing/bw-source/static/node_modules/urllib/lib/urllib.js:517:14)
    at IncomingMessage.<anonymous> (/Users/wing/bw-source/static/node_modules/urllib/lib/urllib.js:658:7)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
`

**Comment by GuGaobai1994** [comment]
可以抓包看下具体请求

**Comment by jemygraw** [comment]
从错误看，你是被重定向到一个内网地址了http://172.16.40.253:80/disable/disable.htm
