### ISSUE TITLE
asyncWrite is not a function

### ISSUE THREAD

**Issue by chenzeZzz** [qiniu/nodejs-sdk#304]
```
Error: /home/dev/backend/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:458
      asyncWrite(afterWrite, stream, state, finished, cb);
      ^

TypeError: asyncWrite is not a function
    at onwrite (/home/dev/backend/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:458:7)
    at WritableState.onwrite (/home/dev/backend/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:169:5)
    at ConcatStream._write (/home/dev/backend/node_modules/concat-stream/index.js:46:3)
    at doWrite (/home/dev/backend/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/home/dev/backend/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:395:5)
    at ConcatStream.Writable.write (/home/dev/backend/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:322:11)
    at Socket.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)

    at doRequest (/home/dev/backend/node_modules/sync-request/index.js:27:11)
    at Object.exports.up_host (/home/dev/backend/node_modules/qiniu/qiniu/zone.js:34:15)
    at putReadable (/home/dev/backend/node_modules/qiniu/qiniu/io.js:55:8)
    at Object.putFile (/home/dev/backend/node_modules/qiniu/qiniu/io.js:120:10)
    at /home/dev/backend/app/common/service/qiniu.js:43:26
    at Generator.next (<anonymous>)
    at step (/home/dev/backend/app/common/service/qiniu.js:21:191)
    at /home/dev/backend/app/common/service/qiniu.js:21:437
    at new Promise (<anonymous>)
    at /home/dev/backend/app/common/service/qiniu.js:21:99
    at module.exports.uploadFile (/home/dev/backend/app/common/service/qiniu.js:56:7)
    at /home/dev/backend/app/common/service/qiniu.js:79:26
    at Generator.next (<anonymous>)
    at step (/home/dev/backend/app/common/service/qiniu.js:21:191)
    at /home/dev/backend/app/common/service/qiniu.js:21:437
    at new Promise (<anonymous>)
```
不确定是那个环节除了问题，而且是几分钟就报错， 没有调七牛的api也会报错 node版本是8.9.4

**Comment by jemygraw** [comment]
这个给下nodejs-sdk的版本把，另外还有你调用的代码。

**Comment by chenzeZzz** [comment]
@jemygraw 
```
import qiniu from 'qiniu';
async uploadFile(uptoken, key, localFile) {
    let deferred = think.defer();
    let extra = new qiniu.io.PutExtra();
    qiniu.io.putFile(uptoken, key, localFile, extra, (err, ret) => {
      if (!err) {
        // 上传成功， 处理返回值(upload suceessfully, return token)
        ret.url = think.config("qiniu").DOMAIN + '/' + ret.key
        console.debug('qiniu upload url:', ret.url);
        deferred.resolve(ret);
      } else {
        // 上传失败， 处理返回代码(upload failed, deal with retun data)
        console.error('上传失败', err);
        deferred.resolve(false);
      }
    });
    return deferred.promise;
  }
```
 "qiniu": "^6.1.13", 会不会和babel 有关系，
编译后的js是 
```
//构造上传函数
  uploadFile(uptoken, key, localFile) {
    return _asyncToGenerator(function* () {
      let deferred = think.defer();
      let extra = new _qiniu2.default.io.PutExtra();
      _qiniu2.default.io.putFile(uptoken, key, localFile, extra, function (err, ret) {
        if (!err) {
          // 上传成功， 处理返回值
          ret.url = think.config("qiniu").DOMAIN + '/' + ret.key;
          console.debug('qiniu upload url:', ret.url);
          deferred.resolve(ret);
        } else {
          // 上传失败， 处理返回代码
          console.error('上传失败', err);
          deferred.resolve(false);
        }
      });
      return deferred.promise;
    })();
  }
```
昨天去七牛的客服问，说是和多进程有关，但是不可能不支持并发的， 从昨晚12点到早上8点， 一共报错103次，晚上的流量不会调那么多次qiniu（这个service api负责上传）

**Comment by jemygraw** [comment]
这个版本过于旧了，如果可以尝试在测试环境升级到最新的sdk看看。

**Comment by chenzeZzz** [comment]
最新的是7.*， 目前稳定版本是哪一个

**Comment by jemygraw** [comment]
7.2.1
