### ISSUE TITLE
uploadToken时报Key must be a buffer

### ISSUE THREAD

**Issue by hpyer** [qiniu/nodejs-sdk#314]
### 错误信息

```
TypeError: Key must be a buffer
    at new Hmac (crypto.js:117:16)
    at Object.Hmac (crypto.js:115:12)
    at Object.exports.hmacSha1 (/Users/hpyer/workspace/chinapost/zjemsbmt/node_modules/qiniu/qiniu/util.js:61:21)
    at PutPolicy.uploadToken (/Users/hpyer/workspace/chinapost/zjemsbmt/node_modules/qiniu/qiniu/storage/rs.js:785:22)
    at Promise (/Users/hpyer/workspace/chinapost/zjemsbmt/server/services/file.js:93:39)
    at new Promise (<anonymous>)
    at _doUpload (/Users/hpyer/workspace/chinapost/zjemsbmt/server/services/file.js:88:16)
    at module.exports.uploadToQiniu (/Users/hpyer/workspace/chinapost/zjemsbmt/server/services/file.js:112:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

### 代码
```js
var mac = new qiniu.auth.digest.Mac(accessKey, secretKey);
var putPolicy = new qiniu.rs.PutPolicy({
  scope: bucket
});
var uploadToken = putPolicy.uploadToken(mac);
var config = new qiniu.conf.Config();
config.zone = qiniu.zone[zone];
var formUploader = new qiniu.form_up.FormUploader(config);
var putExtra = new qiniu.form_up.PutExtra();
var readableStream = fs.createReadStream(file.path); // 可读的流
formUploader.putStream(uploadToken, targetPath, readableStream, putExtra, function(respErr, respBody, respInfo) {
  if (respErr) {
    throw respErr;
  }
  if (respInfo.statusCode == 200) {
    reslove(respBody);
  } else {
    reject(respBody);
  }
});
```

其中accessKey、secretKey、bucket、zone，都是配置的，file是文件上传后的File对象，看不出和示例代码有什么不同～

**Comment by hpyer** [comment]
重复贴
