### ISSUE TITLE
文件上传失败

### ISSUE THREAD

**Issue by gebin** [qiniu/nodejs-sdk#322]
SDK版本号
`
"qiniu": "^7.2.1",
`

报错信息
> upload error:: { ResponseTimeoutError: Response timeout for 120000ms, POST http://up.qiniup.com -1 (connected: true, keepalive socket: false)
headers: {}
    at Timeout._onTimeout (/home/gitlab-runner/builds/9383b49c/0/fe/fe-bms/kdj-www/node_modules/urllib/lib/urllib.js:734:15)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
  name: 'ResponseTimeoutError',
  requestId: 160,
  data: undefined,
  path: '/',
  status: -1,
  headers: {},
  res: 
   { status: -1,
     statusCode: -1,
     headers: {},
     size: 0,
     aborted: false,
     rt: 120028,
     keepAliveSocket: false,
     data: undefined,
     requestUrls: [ 'http://up.qiniup.com' ],
     timing: null,
     remoteAddress: '183.131.7.5',
     remotePort: 80 } } /home/gitlab-runner/builds/9383b49c/0/fe/fe-bms/kdj-www/public/assets/build/1a3b17a65fd05a7c/app.1a3b17a65fd05a7c.js

app.1a3b17a65fd05a7c.js 文件是598k。

**Comment by yi-ge** [comment]
文件很小，但是超时了，说明上传速度实在是慢。我也遇到同样的问题，可以尝试使用分片上传或者调整超时时间。

**Comment by gebin** [comment]
还是使用qshell上传了，node版本会存在很多未知问题

**Comment by musicode** [comment]
这个问题非常频繁，官方有啥解决办法吗？

**Comment by musicode** [comment]
```
2019-06-21 11:31:49,098 ERROR 14137 nodejs.ResponseTimeoutError: Response timeout for 120000ms, POST http://upload-z2.qiniup.com/mkblk/3647951 -1 (connected: true, keepalive socket: false)
headers: {} (uncaughtException throw 1 times on pid:14137)
headers: {} (uncaughtException throw 1 times on pid:14137)
    at Timeout._onTimeout (/home/webroot/repos/www-rd/node_modules/qiniu/node_modules/urllib/lib/urllib.js:734:15)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ResponseTimeoutError"
requestId: 11
data: undefined
path: "/mkblk/3647951"
status: -1
headers: {}
res: {"status":-1,"statusCode":-1,"headers":{},"size":0,"aborted":false,"rt":120075,"keepAliveSocket":false,"requestUrls":["http://upload-z2.qiniup.com/mkblk/3647951"],"timing":null,"remoteAddress":"113.105.138.13","remotePort":80}
pid: 14137
hostname: al-bj-jrd-prod01

2019-06-21 11:31:49,235 ERROR 14131 nodejs.ResponseTimeoutError: Response timeout for 120000ms, POST http://upload-z2.qiniup.com/mkblk/3642044 -1 (connected: true, keepalive socket: false)
headers: {} (uncaughtException throw 2 times on pid:14131)
headers: {} (uncaughtException throw 2 times on pid:14131)
    at Timeout._onTimeout (/home/webroot/repos/www-rd/node_modules/qiniu/node_modules/urllib/lib/urllib.js:734:15)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ResponseTimeoutError"
requestId: 12
data: undefined
path: "/mkblk/3642044"
status: -1
headers: {}
res: {"status":-1,"statusCode":-1,"headers":{},"size":0,"aborted":false,"rt":120041,"keepAliveSocket":false,"requestUrls":["http://upload-z2.qiniup.com/mkblk/3642044"],"timing":null,"remoteAddress":"14.152.37.25","remotePort":80}
pid: 14131
hostname: al-bj-jrd-prod01
```

我现在一查错误日志，全是七牛的...

**Comment by superstrings** [comment]
哈哈哈

**Comment by superstrings** [comment]
maybe??

server.keepAliveTimeout#
Added in: v6.17.0
<number> Timeout in milliseconds. Defaults to 5000 (5 seconds).
The number of milliseconds of inactivity a server needs to wait for additional incoming data, after it has finished writing the last response, before a socket will be destroyed. If the server receives new data before the keep-alive timeout has fired, it will reset the regular inactivity timeout, i.e., server.timeout.

A value of 0 will disable the keep-alive timeout behavior on incoming connections.

Note: The socket timeout logic is set up on connection, so changing this value only affects new connections to the server, not any existing connections.
