### ISSUE TITLE
上传超时，出现的非常频繁

### ISSUE THREAD

**Issue by musicode** [qiniu/nodejs-sdk#336]
版本：7.2.1

```
2019-06-21 11:31:49,098 ERROR 14137 nodejs.ResponseTimeoutError: Response timeout for 120000ms, POST http://upload-z2.qiniup.com/mkblk/3647951 -1 (connected: true, keepalive socket: false)
headers: {} (uncaughtException throw 1 times on pid:14137)
headers: {} (uncaughtException throw 1 times on pid:14137)
    at Timeout._onTimeout (/home/webroot/repos/www-rd/node_modules/qiniu/node_modules/urllib/lib/urllib.js:734:15)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ResponseTimeoutError"
requestId: 11
data: undefined
path: "/mkblk/3647951"
status: -1
headers: {}
res: {"status":-1,"statusCode":-1,"headers":{},"size":0,"aborted":false,"rt":120075,"keepAliveSocket":false,"requestUrls":["http://upload-z2.qiniup.com/mkblk/3647951"],"timing":null,"remoteAddress":"113.105.138.13","remotePort":80}
pid: 14137
hostname: al-bj-jrd-prod01

2019-06-21 11:31:49,235 ERROR 14131 nodejs.ResponseTimeoutError: Response timeout for 120000ms, POST http://upload-z2.qiniup.com/mkblk/3642044 -1 (connected: true, keepalive socket: false)
headers: {} (uncaughtException throw 2 times on pid:14131)
headers: {} (uncaughtException throw 2 times on pid:14131)
    at Timeout._onTimeout (/home/webroot/repos/www-rd/node_modules/qiniu/node_modules/urllib/lib/urllib.js:734:15)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ResponseTimeoutError"
requestId: 12
data: undefined
path: "/mkblk/3642044"
status: -1
headers: {}
res: {"status":-1,"statusCode":-1,"headers":{},"size":0,"aborted":false,"rt":120041,"keepAliveSocket":false,"requestUrls":["http://upload-z2.qiniup.com/mkblk/3642044"],"timing":null,"remoteAddress":"14.152.37.25","remotePort":80}
pid: 14131
hostname: al-bj-jrd-prod01
```

**Comment by JackPu** [comment]
同样的问题，经常遇见有谁解决了么？

**Comment by beimengyeyu** [comment]
> 同样的问题，经常遇见有谁解决了么？

同样的问题，10M左右就会出现。可能因为我走的是Github Action不是走的国内网络的原因吧，大致看了一下代码，貌似超时时间是写死的，因此我用patch-package打了一个补丁，让他可以变成可配置的，如果您想用和我类似的解决方式，可以用类似的策略处理。
